###################################################################
#                                                                 #
#                            Negativity                           #
#                      AntiCheat by Elikill58                     #
#                                                                 #
#              If you have a problem or a suggestion,             #
#                    You can contact me on:                       #
#                  - Discord: @Elikill58#0743                     #
#       - my Discord server: https://discord.gg/KHRVTX2           #
#               - Mail: arpetzouille@gmail.com                    #
#                   - SpigotMC: Elikill58                         #
#                  - Minecraft.fr: Elikill                        #
#                                                                 #
###################################################################

Database:
  isActive: false
  # To get the information. We use the player uuid to get the information.
  # We get only what you write. We never add or remove something.
  # We don't save your private information about your database
  url: "127.0.0.1/myDb"
  user: root
  password: "myPassword"
  table_lang: "myTable"
  table_ban: "ban"
  column_lang: "lang"
  saveInCache: false # To do less request to your database

Permissions:
  # The checker indicates if a player has a specific permission.
  # By default only 'platform' is available
  checker: platform
  showAlert:
    default: "negativity.alert"
  admin:
    default: "negativity.admin"
  showReport:
    default: "negativity.seereport"
  # To bypass ban system
  notBanned:
    default: "negativity.notbanned"

Translation:
  active: false # enable or disable the translation
  lang_available:
  - de_DE
  - en_US
  - fr_FR
  - nl_NL
  - no_NO
  - pt_BR
  - ru_RU
  - sv_SV
  - zh_CN
  - es_ES
  - vi_VN
  - pl_PL
  use_db: false # to get the lang
  default: en_US
  # The provider used to get translated messages, useful if you want to customize the way Negativity gets its messages.
  # The only one available out-of-the-box is "platform".
  provider: platform
